# Generated by Django 4.1.6 on 2023-02-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
