# Generated by Django 4.1.6 on 2023-02-10 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0002_remove_buyer_email_remove_buyer_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
