# Generated by Django 4.1.6 on 2023-02-10 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0004_bill_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='user',
            new_name='buyer',
        ),
    ]
